2022-10-17 15:55:04,972 INFO    Thread-8  :67573 [wandb_setup.py:_flush():68] Configure stats pid to 67573
2022-10-17 15:55:04,972 INFO    Thread-8  :67573 [wandb_setup.py:_flush():68] Loading settings from /Users/zorilolah/.config/wandb/settings
2022-10-17 15:55:04,972 INFO    Thread-8  :67573 [wandb_setup.py:_flush():68] Loading settings from /Users/zorilolah/Documents/CryptoNewsFeed/wandb/settings
2022-10-17 15:55:04,972 INFO    Thread-8  :67573 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True', 'project': 'test123', 'entity': 'zoril', 'root_dir': '/Users/zorilolah/Documents/CryptoNewsFeed', 'run_id': '5lk5x22n', 'sweep_param_path': '/Users/zorilolah/Documents/CryptoNewsFeed/wandb/sweep-bu0h7rsq/config-5lk5x22n.yaml', 'sweep_id': 'bu0h7rsq'}
2022-10-17 15:55:04,972 INFO    Thread-8  :67573 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'src/run_wandb_swipe.py', 'program': '/Users/zorilolah/Documents/CryptoNewsFeed/src/run_wandb_swipe.py'}
2022-10-17 15:55:04,973 INFO    Thread-8  :67573 [wandb_init.py:_log_setup():476] Logging user logs to /Users/zorilolah/Documents/CryptoNewsFeed/wandb/run-20221017_155504-5lk5x22n/logs/debug.log
2022-10-17 15:55:04,973 INFO    Thread-8  :67573 [wandb_init.py:_log_setup():477] Logging internal logs to /Users/zorilolah/Documents/CryptoNewsFeed/wandb/run-20221017_155504-5lk5x22n/logs/debug-internal.log
2022-10-17 15:55:04,973 INFO    Thread-8  :67573 [wandb_init.py:init():516] calling init triggers
2022-10-17 15:55:04,973 INFO    Thread-8  :67573 [wandb_init.py:init():519] wandb.init called with sweep_config: {'batch_size': 64, 'epochs': 5, 'lr': 0.0015198697834052006, 'scheduler_form': 'linear', 'wd': 0.008119668706201929}
config: {}
2022-10-17 15:55:04,973 INFO    Thread-8  :67573 [wandb_init.py:init():569] starting backend
2022-10-17 15:55:04,973 INFO    Thread-8  :67573 [wandb_init.py:init():573] setting up manager
2022-10-17 15:55:04,978 INFO    Thread-8  :67573 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-10-17 15:55:04,984 INFO    Thread-8  :67573 [wandb_init.py:init():580] backend started and connected
2022-10-17 15:55:04,990 INFO    Thread-8  :67573 [wandb_run.py:_config_callback():1160] config_cb None None {'batch_size': 64, 'epochs': 5, 'lr': 0.0015198697834052006, 'scheduler_form': 'linear', 'wd': 0.008119668706201929}
2022-10-17 15:55:04,995 INFO    Thread-8  :67573 [wandb_init.py:init():658] updated telemetry
2022-10-17 15:55:05,023 INFO    Thread-8  :67573 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-10-17 15:55:05,412 INFO    Thread-8  :67573 [wandb_run.py:_on_init():2000] communicating current version
2022-10-17 15:55:05,462 INFO    Thread-8  :67573 [wandb_run.py:_on_init():2004] got version response 
2022-10-17 15:55:05,463 INFO    Thread-8  :67573 [wandb_init.py:init():728] starting run threads in backend
2022-10-17 15:55:10,329 ERROR   Thread-8  :67573 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/Users/zorilolah/anaconda3/envs/vit/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/Users/zorilolah/anaconda3/envs/vit/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 739, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/Users/zorilolah/anaconda3/envs/vit/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 235, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "/Users/zorilolah/anaconda3/envs/vit/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 484, in _communicate_run_start
    result = self._communicate(rec)
  File "/Users/zorilolah/anaconda3/envs/vit/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 255, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/zorilolah/anaconda3/envs/vit/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 36, in get
    is_set = self._object_ready.wait(timeout)
  File "/Users/zorilolah/anaconda3/envs/vit/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/zorilolah/anaconda3/envs/vit/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
Exception
2022-10-17 15:55:15,157 WARNING MsgRouterThr:67573 [router.py:message_loop():77] message_loop has been closed
